### ISSUE TITLE
个人建议既然开源要有诚意

### ISSUE THREAD

**Issue by itwork** [MiCode/FileExplorer#12]
为什么要基于4.0的SDK呢，我觉得完全可以用肯定版本的，这样有利于开发者二次开发，我的邮箱ni@172.com可以发邮件与我联系，也希望浩南哥能给我发一份2.2+的FileExplorer

**Comment by haonan** [comment]
:-)  开源得很有诚意的，如果要支持的更低的版本，你可以做一些修改的，把Fragment改成Activity，改动不大的。基于4.0，是因为想与时俱进，可以用更多高级的控件。

**Comment by itwork** [comment]
个人建议 可以降低 SDK的版本，这样适用范围更加广泛，这才是开源的真谛啊，或者把之前的 2.3.7的代码放出来也好啊，您觉得呢？可以私聊~

**Comment by haonan** [comment]
暂不考虑降低sdk版本。

**Comment by Noisyfox** [comment]
马上拿到青春版就可以继续开始弄

**Comment by Noisyfox** [comment]
话说这个开源版本会不会被用到什么地方的说？

**Comment by haonan** [comment]
嗯 已经有rom使用了。你考试什么时候结束

**Comment by haonan** [comment]
嗯 已经有rom使用了。你考试什么时候结束

**Comment by Noisyfox** [comment]
下周六考完~之后打算去小米之家~~

**Comment by Noisyfox** [comment]
话说2.3miui是不是几乎已经停掉啦？全力开发v4

**Comment by itwork** [comment]
Noisyfox 你有没有2.3的历史版本文件管理器 我个人必要怀旧。

**Comment by itwork** [comment]
求2.3时代的文件管理器

**Comment by SunRain** [comment]
这个就不要想了，既然故意用ics的sdk来开源，你认为会把2.3的代码给你？

**Comment by haonan** [comment]
2.3和4.0的代码基本都一样的，无非在4.0中使用了一些特殊的控件，如：滑动切换tab等。自己感兴趣，完全可以改为2.3的，作为程序员，这个有什么好争论的，看看代码中了用了什么4.0的系统控件，删掉或者改为2.3的就可以了。这个问题就回复到这里了。囧～

**Comment by itwork** [comment]
我之前就已经改了，谢谢MIUI团队。
