### ISSUE TITLE
从远程管理页面切换出来会有卡顿

### ISSUE THREAD

**Issue by Noisyfox** [MiCode/FileExplorer#13]
rt，不知道是哪里的代码，做了什么事情也不知道（貌似是刷新分类？），相关的代码不是很明白，求指点

**Comment by haonan** [comment]
这个已经修复了。我明天提交代码，你看下。

**Comment by lishunli** [comment]
确实是有这样的问题，希望尽快 commit code

**Comment by haonan** [comment]
已经提交代码了，请验证效果是否理想。tab切换，避免重新createView而出现的卡顿

**Comment by Noisyfox** [comment]
确实不卡了，不过为什么参数是2？

**Comment by Noisyfox** [comment]
难道说第三个page的编号是2？

**Comment by haonan** [comment]
你看一下修改的summary。默认的值为1， 所以在tab切换的时候，会有recreate，会有数据加载，导致卡。现在设为2，就全部在内存里。
ViewPager.java类中的setOffscreenPageLimit函数的注释：
If you have a small number of pages (3-4)
that you can keep active all at once, less time will be spent in layout for
newly created view subtrees as the user pages back and forth.

**Comment by haonan** [comment]
你看一下修改的summary。默认的值为1， 所以在tab切换的时候，会有recreate，会有数据加载，导致卡。现在设为2，就全部在内存里。
ViewPager.java类中的setOffscreenPageLimit函数的注释：
If you have a small number of pages (3-4)
that you can keep active all at once, less time will be spent in layout for
newly created view subtrees as the user pages back and forth.

**Comment by Noisyfox** [comment]
查了下ViewPage预加载的资料明白了
