### ISSUE TITLE
文件管理器的图标异常

### ISSUE THREAD

**Issue by lishunli** [MiCode/FileExplorer#14]
测试环境： MIUI4-6.1+ MI One Plus, 具体的看截图，相信清楚出现了什么。
我也尝试过修改 icon 图片（拿到原版的文件管理器的覆盖），不过好像没有效果，请帮忙解决。

![图标异常](http://usc.googlecode.com/files/icon-error.png)

**Comment by haonan** [comment]
miui中，第三方的app会有一个背景的。

**Comment by lishunli** [comment]
不太明白，何为 第三方 Apps ？ 为什么其他 apk 不会这样，有什么办法可以解决？ 签名生成 apk？

**Comment by haonan** [comment]
不是系统自带的就是第三方的。有些第三方的软件，我们放在一个列表中，也提供了默认的icon。其他的第三方，就会有一个背景。

**Comment by Noisyfox** [comment]
这个问题去我在论坛有提过解决办法，只要把包的名字改成com.android.fileexplorer就好了，不过就没办法直接用eclipse安装进去了

**Comment by lishunli** [comment]
看到论坛中的了，算是一个还算可以的解决方案吧，真的要在 Java 修改package 名（注意全部修改，包括很多配置文件），还要替换 /system/app 中的文件（如果没有的话，安装成功但是看不见图标，MIUI 做了什么事情不清楚）。 这样替换有点麻烦，而且刷机后应该就没有了，不管怎么说，这样使用先。 http://micode.net/thread-187-1-1.html
