### ISSUE TITLE
无法导入Eclipse怎么解决？

### ISSUE THREAD

**Issue by HanderWei** [MiCode/FileExplorer#22]
导入到最后显示 No projects found

由于没有project.properties吧
@lamb @Noisyfox  请问你们是怎么将这个项目导入到Eclipse的

非常感谢！

**Comment by Noisyfox** [comment]
Import -> Existing Android Code Into Workspace

**Comment by HanderWei** [comment]
No project found.

Because the git project  doesn't have project.properties

------------------ 原始邮件 ------------------
发件人: "Noisyfox";notifications@github.com;
发送时间: 2014年3月16日(星期天) 下午4:12
收件人: "MiCode/FileExplorer"FileExplorer@noreply.github.com; 
抄送: "陈威"583275879@qq.com; 
主题: Re: [FileExplorer] 无法导入Eclipse怎么解决？ (#22)

Import -> Existing Android Code Into Workspace

**Comment by Noisyfox** [comment]
不需要啊只要有AndroidManifest.xml就可以导入啊

**Comment by HanderWei** [comment]
@Noisyfox  非常感谢  问题解决了 

第一次用GitHub  很不熟悉

**Comment by flyingsnowers** [comment]
怎么解决的呢

**Comment by HanderWei** [comment]
@flyingsnowers  download zip 然后解压到一个目录（不能是workspace）
然后再eclipse import  -> Existing Android Code into workspace  ->选择刚才解压的文件夹即可

**Comment by flyingsnowers** [comment]
太感谢了！谢谢，弄好了！

------------------ 原始邮件 ------------------
发件人: "HanderWei";notifications@github.com;
发送时间: 2014年3月19日(星期三) 下午2:39
收件人: "MiCode/FileExplorer"FileExplorer@noreply.github.com; 
抄送: "飞雪"1074272823@qq.com; 
主题: Re: [FileExplorer] 无法导入Eclipse怎么解决？ (#22)

@flyingsnowers  download zip 然后解压到一个目录（不能是workspace）
 然后再eclipse import  -> Existing Android Code into workspace  ->选择刚才解压的文件夹即可
