### ISSUE TITLE
不能复制文件夹？

### ISSUE THREAD

**Issue by Noisyfox** [MiCode/FileExplorer#9]
话说我试了2.3的miui文件管理器，一样不能复制文件夹，这是故意的还是bug？

**Comment by haonan** [comment]
2.3和现在文件浏览器都可以复制文件夹的。

**Comment by Noisyfox** [comment]
好吧。。发现加了
if(selectedNum == 0){
mode.finish();
 }
以后各种bug。。。好奇怪。。。还是得把代码仔细读一读。。。

**Comment by Noisyfox** [comment]
貌似不能复制空的文件夹？

**Comment by Noisyfox** [comment]
现在问题是每次点了删除文件以后弹出的“正在删除”的对话框一直不会消失。。。也不知道是哪里控制的

**Comment by haonan** [comment]
正在删除的对话框可以消失的，就是有些慢。

**Comment by Noisyfox** [comment]
这是为什么？是什么语句控制的这个对话框的消失呢？
